export const LINKS = {
  rules: "/rules",
  register: "https://forms.gle/zyMBnQFeUHyb6CFB9",
  contact1: "https://www.instagram.com/harufest_soushin?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw%3D%3D",
  contact2: "https://api.whatsapp.com/send/?phone=6282154803352&text&type=phone_number&app_absent=0",
  freetime: "https://www.instagram.com/freetime.ofc?igsh=MWkwaDdlc21ud2Q1",
  gwen: "https://www.instagram.com/16wen_?igsh=MWs2cjFtZXZnYmN6eg==",
  miirukat: "https://www.instagram.com/miirukat?igsh=bmZiZmhob2g1cmdn",
  cherry: "https://www.instagram.com/cherrytime21?igsh=eHIzZmRvcHRnOGpv",
  kethy: "https://www.instagram.com/kethyy_sond?igsh=cXFjbG91M28xbm4z",
  abi: "https://www.instagram.com/donrafdie?igsh=MWg0emNnb3Y4N2phcw==",
  meia: "https://www.instagram.com/seiameia?igsh=MTAweTdzZnNsN21mdA==",
  anggoro: "https://www.instagram.com/anggorodwi22?igsh=Z3AyOGVsYWZzbHIy",
  tatonary: "https://www.instagram.com/tatonary?igsh=MTR5MmFjam5xMXdvdA==",
  stipeanut: "https://www.instagram.com/stipeanut?igsh=dXlyY3IzOWdpZGtr",
};